baseURL = "/"
languageCode = "en-uk"
title = "New Zealand Open Research Network"
theme = "timer-hugo"

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
# We Used Ionicons Icon font for Icon, for more details check this link - https://ionicons.com/

# Site Menus
[menu]
    # Navbar Menus
    [[menu.nav]]
        name    = "About"
        url     = "/about"
        weight  = 2
    [[menu.nav]]
        name    = "Code of Conduct"
        url     = "/Code_of_Conduct"
        weight  = 3
    #[[menu.nav]]
    #    name    = "Gallery"
    #    url     = "/gallery"
    #    weight  = 4
    [[menu.nav]]
        name    = "Articles"
        url     = "/blog"
        weight  = 4
    [[menu.nav]]
        name    = "Resources"
        url     = "/Resources"
        weight  = 5
    #[[menu.nav]]
    #    name    = "Contact"
    #    url     = "/contact"
    #    weight  = 4

# Site Params
[params]
    home = "Home"
    logo = "images/web_logo_small.png"
    dateFormat = "6 January 2006"

    # Banner Section
    [params.banner]
        enable  = true
        bgImage = "images/bg.jpg"
        heading = "WELCOME TO THE NEW ZEALAND OPEN RESEARCH NETWORK"
        description = "A hub for Open Research practitioners in New Zealand."
        #btn     = true
        #btnText = "Download More"
        #btnURL  = "https://themefisher.com/"
        [[params.banner.flipText]]
            title   = "COMMUNITY"
        [[params.banner.flipText]]
            title   = "ADVOCACY"
        [[params.banner.flipText]]
            title   = "EDUCATION"

    # Homepage About Section
    [params.about]
        enable  = true
        title   = "ABOUT THE NETWORK"
        content = "Open science and open research practices are growing in New Zealand, but discovering open research can feel like an isolating experience. This is a mechanism to promote open science and open practices in New Zealand, to build a sense of community amongst people who might otherwise feel like the only open researchers they know. <br>We aim to help you find like-minded folks, support efforts to reform institutional policies and practices, and educate others about open research."
        image   = "images/about/invert.png"

    # Call to Action
    [params.cta]
        enable  = true
        title   = "GET INVOLVED!"
        content = "</br>Follow our <a href='https://twitter.com/NZOpenRes'>Twitter account</a>, sign up to our <a href='https://groups.google.com/forum/#!forum/nzopenres'>Google Group</a>, or join us and our Aussie compatriots in the Australia/New Zealand slack workspace by filling out <a href='http://eepurl.com/gat7QH'>this survey</a>.</br></br>NZORN is an inclusive and welcoming community by design. To preserve this, NZORN activities are subject to our Code of Conduct (see the Code of Conduct tab above)."
        btnText = "Contact us"
        btnURL  = "https://groups.google.com/d/contactowner/nzopenres"

    # Portfolio Section On Homepage
    [params.portfolio]
        enable  = true
        title   = "LOCAL COMMUNITIES"
        subtitle= "Want to find some open science advocates near you? Check out some of our institutional communities."

    # Feature Product Section
    [params.feature]
        enable  = false
        title   = "SOME OF OUR FEATURES WORKS"
        subtitle= "Aliquam lobortis. Maecenas vestibulum mollis diam. Pellentesque auctor neque nec urna. Nulla sit amet est. Aenean posuere <br> tortor sed cursus feugiat, nunc augue blandit nunc, eu sollicitudin urna dolor sagittis lacus."

    
